### ISSUE TITLE
History Class

### ISSUE THREAD

**Issue by vasiliskyriakos** [VasilisKyriakos/financial-wallet#1]
Έχουμε υλοποιήσει στην κλάση BankAccount ένα αντικείμενο της κλάσης Transactions ,επομένως με αυτό τον τρόπο το κάθε Bank Account έχει ένα δικό του transaction list. Θα πρέπει να συμπεριλάβουμε όλα αυτά τα transactions και να τα οργανώσουμε για να φτιαχτεί η κλάση History.

**Comment by kyrlm** [comment]
Η κλάση History έγινε. Εμφανίζονται τα transactions του χρήστη που συνδέεται και μπορεί να επιλέξει και κατηγορία.

**Comment by vasiliskyriakos** [comment]
Ωραία επομένως θα θεωρήσω το τρέχον  issue  λήξαν.
