### ISSUE TITLE
Try catch Exception in  chooseBankAccount

### ISSUE THREAD

**Issue by ThodorosChatz** [VasilisKyriakos/financial-wallet#2]
The Method only works with integers. It crashes with character etc.

**Comment by vasiliskyriakos** [comment]
Ναι θα συμπεριλάβουμε και try catch μεθόδους για να προβλέπουμε τέτοιες συμπεριφορές.

**Comment by vasiliskyriakos** [comment]
Ναι απλά πιστεύω ότι είναι καλύτερο να επικεντρωθούμε στην υλοποίηση των κλάσεων λόγω πίεσης χρόνου.
