### ISSUE TITLE
Transaction Class

### ISSUE THREAD

**Issue by vasiliskyriakos** [VasilisKyriakos/financial-wallet#3]
Καθώς οι κλάσεις Payment , First Party Transfer και Peer to Peer μοιάζουν θα πρέπει να τα υλοποιήσουμε όλα σε μια γενικότερη κλάση Transaction όπως και κάναμε , είτε να παίξουμε με κληρονομικότητες αλλά θα έχουμε αρκετά κενές κλάσεις που κληρονομούν από την Transaction. Tι προρειμάτε;

**Comment by ThodorosChatz** [comment]
Μαζί με τον Βασιλή το κρίναμε αναγκαιό. και για το πετύχουμε προσθέσαμε μια μεταβλήτη type στην κλάση transaction ώστε να φαίνεται ο τύπος της συναλλαγης

**Comment by vasiliskyriakos** [comment]
Ωραία άρα το θέμα έχει λυθεί και κάνω close το issue. Αλλιώς θα ξαναγίνει reopen για περαιτέρω συζήτηση.
